name: My Kata

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hexa-archi_bank-account:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build bank account
        working-directory: hexa-archi/bank-account
        run: mvn --batch-mode --update-snapshots package
      

  TDD_black-jack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build black jack
        working-directory: TDD/black-jack
        run: mvn --batch-mode --update-snapshots package


  TDD_coffee-machine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build coffee machine
        working-directory: TDD/coffee-machine
        run: mvn --batch-mode --update-snapshots package

  TDD_fizz-buzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build fizz buzz
        working-directory: TDD/fizz-buzz
        run: mvn --batch-mode --update-snapshots package

  TDD_fraction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build fraction
        working-directory: TDD/fraction
        run: mvn --batch-mode --update-snapshots package

  TDD_mars-rover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: mars rover
        working-directory: TDD/mars-rover
        run: mvn --batch-mode --update-snapshots package

  TDD_tondeuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: tondeuse
        working-directory: TDD/tondeuse
        run: mvn --batch-mode --update-snapshots package
